// Code generated by go generate; DO NOT EDIT.
package entities

type LightDomain struct {
	LightPv string
}

var Light = LightDomain{
	LightPv: "light.pv_lampe_licht",
}

type SensorDomain struct {
	EnergyGridPower string
}

var Sensor = SensorDomain{
	EnergyGridPower: "sensor.powerocean_sysgridpwr",
}

type ZoneDomain struct {
	HomeZone string
}

var Zone = ZoneDomain{
	HomeZone: "zone.home",
}

