// Package main provides the generate command for generating Home Assistant entity constants.
// Run via: go generate ./... (or go run ./cmd/generate)
// Add --validate to connect to HA and verify entities + fetch friendly names.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	ga "saml.dev/gome-assistant"
	"gopkg.in/yaml.v3"
)

type EntityEntry struct {
	EntityID string `yaml:"entity_id"`
	Name     string `yaml:"name"`
}

type Config struct {
	URL              string        `yaml:"url"`
	HAAuthToken      string        `yaml:"ha_auth_token"`
	HomeZoneEntityID string        `yaml:"home_zone_entity_id,omitempty"`
	Entities         []EntityEntry `yaml:"entities"`
}

type Entity struct {
	FieldName string
	EntityID  string
	Comment   string
}

type Domain struct {
	Name     string
	Entities []Entity
}

func toCamelCase(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.Split(s, "_")
	var result strings.Builder
	firstChar := parts[0][0]
	if firstChar >= '0' && firstChar <= '9' {
		result.WriteString("_")
	}
	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(string(part[0])))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}
	return result.String()
}

func generate(config Config, validate bool) error {
	// Syntactic validation and name normalization
	type entry struct {
		fieldName string
		entityID  string
		domainRaw string
	}

	entries := make([]entry, 0, len(config.Entities))
	for _, e := range config.Entities {
		parts := strings.Split(e.EntityID, ".")
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return fmt.Errorf("invalid entity_id %q: must be domain.name", e.EntityID)
		}

		var fieldName string
		if e.Name == "" {
			fieldName = toCamelCase(parts[1])
			fmt.Printf("warning: no name for entity_id %q, using auto-derived field name %q\n", e.EntityID, fieldName)
		} else {
			fieldName = toCamelCase(e.Name)
		}

		entries = append(entries, entry{
			fieldName: fieldName,
			entityID:  e.EntityID,
			domainRaw: parts[0],
		})
	}

	// Duplicate detection per domain
	seen := make(map[string]map[string]string) // domain -> fieldName -> entityID
	for _, e := range entries {
		if seen[e.domainRaw] == nil {
			seen[e.domainRaw] = make(map[string]string)
		}
		if existing, ok := seen[e.domainRaw][e.fieldName]; ok {
			return fmt.Errorf("duplicate field name %q in domain %q: used by %q and %q", e.fieldName, e.domainRaw, existing, e.entityID)
		}
		seen[e.domainRaw][e.fieldName] = e.entityID
	}

	// Optional HA validation
	friendlyNames := make(map[string]string)
	if validate {
		if config.URL == "" || config.HAAuthToken == "" {
			return fmt.Errorf("--validate requires url and ha_auth_token (or HA_AUTH_TOKEN env var)")
		}
		homeZone := config.HomeZoneEntityID
		if homeZone == "" {
			homeZone = "zone.home"
		}
		app, err := ga.NewApp(ga.NewAppRequest{
			URL:              config.URL,
			HAAuthToken:      config.HAAuthToken,
			HomeZoneEntityId: homeZone,
		})
		if err != nil {
			return fmt.Errorf("failed to connect to HA: %w", err)
		}
		defer app.Cleanup()

		for _, e := range entries {
			state, err := app.GetState().Get(e.entityID)
			if err != nil {
				fmt.Printf("warning: entity %q not found in HA: %v\n", e.entityID, err)
				continue
			}
			if fn, ok := state.Attributes["friendly_name"].(string); ok && fn != "" {
				friendlyNames[e.entityID] = fn
			}
		}
	}

	// Group by domain
	domainMap := make(map[string]*Domain)
	for _, e := range entries {
		if _, exists := domainMap[e.domainRaw]; !exists {
			domainMap[e.domainRaw] = &Domain{Name: toCamelCase(e.domainRaw)}
		}
		domainMap[e.domainRaw].Entities = append(domainMap[e.domainRaw].Entities, Entity{
			FieldName: e.fieldName,
			EntityID:  e.entityID,
			Comment:   friendlyNames[e.entityID],
		})
	}

	// Stable sort
	domains := make([]Domain, 0, len(domainMap))
	for _, d := range domainMap {
		sort.Slice(d.Entities, func(i, j int) bool {
			return d.Entities[i].FieldName < d.Entities[j].FieldName
		})
		domains = append(domains, *d)
	}
	sort.Slice(domains, func(i, j int) bool {
		return domains[i].Name < domains[j].Name
	})

	if err := os.MkdirAll("entities", 0755); err != nil {
		return fmt.Errorf("failed to create entities directory: %w", err)
	}

	tmpl := template.Must(template.New("entities").Parse(`// Code generated by go generate; DO NOT EDIT.
package entities
{{ range .Domains }}
type {{ .Name }}Domain struct {
{{- range .Entities }}
	{{ .FieldName }} string{{ if .Comment }} // {{ .Comment }}{{ end }}
{{- end }}
}

var {{ .Name }} = {{ .Name }}Domain{
{{- range .Entities }}
	{{ .FieldName }}: "{{ .EntityID }}",
{{- end }}
}
{{ end }}
`))

	f, err := os.Create(filepath.Join("entities", "entities.go"))
	if err != nil {
		return fmt.Errorf("failed to create entities.go: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, struct{ Domains []Domain }{domains})
}

func main() {
	configFile := flag.String("config", "gen.yaml", "Path to config file")
	validate := flag.Bool("validate", false, "Connect to HA to validate entities and fetch friendly names")
	flag.Parse()

	absConfigPath, err := filepath.Abs(*configFile)
	if err != nil {
		fmt.Printf("Error resolving config path: %v\n", err)
		os.Exit(1)
	}

	configBytes, err := os.ReadFile(absConfigPath)
	if err != nil {
		fmt.Printf("Error reading config file: %v\n", err)
		os.Exit(1)
	}

	var config Config
	if err := yaml.Unmarshal(configBytes, &config); err != nil {
		fmt.Printf("Error parsing config file: %v\n", err)
		os.Exit(1)
	}

	if config.HAAuthToken == "" {
		config.HAAuthToken = os.Getenv("HA_AUTH_TOKEN")
	}

	if len(config.Entities) == 0 {
		fmt.Println("Error: no entities defined in config")
		os.Exit(1)
	}

	fmt.Println("Generating entities/entities.go...")
	if err := generate(config, *validate); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Done.")
}
